name: 'Terraform'

on:
  push:
    branches: [main]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform Container App'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Initialize Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.1.0"

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/atca
    
    - name: Terraform Apply
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
      run: terraform apply -auto-approve -var github_access_token=${{ env.GITHUB_ACCESS_TOKEN }} -var github_project_name=${{ env.GITHUB_PROJECT_NAME }} -var github_username=${{ env.GITHUB_USERNAME }}
      working-directory: terraform/atca