name: 'test'

on:
  [workflow_dispatch]

defaults:
    run:
        shell: bash

jobs: 
    ci_test:
        runs-on: ubuntu-latest
        name: 'Continuous implementation of our .NET code'
        steps:
            - uses: actions/checkout@v3
            - name: Checking download of files
              run: ls -la
#            - name: Lint .NET
#              uses: zyactions/dotnet-lint@v1
#              with:
#                workspace: app
#                implicit-restore: true
            - uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: '7'
            - name: Test .NET
              run: dotnet test
            - name: Build .NET
              run: dotnet build
            - name: Checking generated files by the build
              run: ls -la
            - name: Store build files
              uses: actions/upload-artifact@v3
              with:
                name: build_binary
                path: app/bin  
            - name: Store Terraform project
              uses: actions/upload-artifact@v3
              with:
                name: terraform_project
                path: terraform/atvm
                
    cd_test:
        name: 'Continuous deployment of our .NET code using terraform'
        runs-on: ubuntu-latest
        needs: [ci_test]
        steps:
            - name: Download Build files
              uses: actions/download-artifact@v3
              with:
                name: build_binary
                path: app
            - name: Download Build files
              uses: actions/download-artifact@v3
              with:
                name: terraform_project
                path: terraform
            - name: Checking download of files
              run: ls -la
            - name: Initialize Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: "1.4.6"

            - name: Terraform Init
              run: terraform init
              working-directory: terraform

            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDS }}

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: terraform

    failure_control:
        needs: [ci_test, cd_test]
        if: failure()
        runs-on: ubuntu-latest
        name: Failure
        steps:
            - run: echo 'failure found' 

    success_control:
        needs: [ci_test, cd_test]
        if: success()
        runs-on: ubuntu-latest
        name: Success
        steps:
            - run: echo 'all working'