name: 'test'

on:
  pull_request:
    branches:    
    - main
  push:
    branches:
    - main

defaults:
    run:
        shell: bash

jobs: 
    ci_test:
        runs-on: ubuntu-latest
        name: CI Test of our code
        steps:
            - uses: actions/checkout@v3
            - run: ls -la

    echo_ing_:
        needs: [ci_test]
        runs-on: ubuntu-latest
        name: echoing the folder content
        steps:
            - run: ls -la


    echo_github_data:
        runs-on: ubuntu-latest
        name: Echo-ing- github dictionary
        steps:
            - run: echo '${{ toJSON(github) }}'